include: package:very_good_analysis/analysis_options.yaml
linter:
    rules:
        public_member_api_docs: true
        close_sinks: true
        one_member_abstracts: true
analyzer:
    exclude:
        - lib/generated_plugin_registrant.dart
